// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package com.companyname.project.proto;

public final class Metadata {
  private Metadata() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KeyValueProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:KeyValueProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>required string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code KeyValueProto}
   */
  public static final class KeyValueProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:KeyValueProto)
      KeyValueProtoOrBuilder {
    // Use KeyValueProto.newBuilder() to construct.
    private KeyValueProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeyValueProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeyValueProto defaultInstance;
    public static KeyValueProto getDefaultInstance() {
      return defaultInstance;
    }

    public KeyValueProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeyValueProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.companyname.project.proto.Metadata.internal_static_KeyValueProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.companyname.project.proto.Metadata.internal_static_KeyValueProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.companyname.project.proto.Metadata.KeyValueProto.class, com.companyname.project.proto.Metadata.KeyValueProto.Builder.class);
    }

    public static com.google.protobuf.Parser<KeyValueProto> PARSER =
        new com.google.protobuf.AbstractParser<KeyValueProto>() {
      public KeyValueProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeyValueProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeyValueProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    /**
     * <code>required string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.companyname.project.proto.Metadata.KeyValueProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.companyname.project.proto.Metadata.KeyValueProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.companyname.project.proto.Metadata.KeyValueProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.companyname.project.proto.Metadata.KeyValueProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.companyname.project.proto.Metadata.KeyValueProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.companyname.project.proto.Metadata.KeyValueProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.companyname.project.proto.Metadata.KeyValueProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.companyname.project.proto.Metadata.KeyValueProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.companyname.project.proto.Metadata.KeyValueProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.companyname.project.proto.Metadata.KeyValueProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.companyname.project.proto.Metadata.KeyValueProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KeyValueProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:KeyValueProto)
        com.companyname.project.proto.Metadata.KeyValueProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.companyname.project.proto.Metadata.internal_static_KeyValueProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.companyname.project.proto.Metadata.internal_static_KeyValueProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.companyname.project.proto.Metadata.KeyValueProto.class, com.companyname.project.proto.Metadata.KeyValueProto.Builder.class);
      }

      // Construct using com.companyname.project.proto.Metadata.KeyValueProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.companyname.project.proto.Metadata.internal_static_KeyValueProto_descriptor;
      }

      public com.companyname.project.proto.Metadata.KeyValueProto getDefaultInstanceForType() {
        return com.companyname.project.proto.Metadata.KeyValueProto.getDefaultInstance();
      }

      public com.companyname.project.proto.Metadata.KeyValueProto build() {
        com.companyname.project.proto.Metadata.KeyValueProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.companyname.project.proto.Metadata.KeyValueProto buildPartial() {
        com.companyname.project.proto.Metadata.KeyValueProto result = new com.companyname.project.proto.Metadata.KeyValueProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.companyname.project.proto.Metadata.KeyValueProto) {
          return mergeFrom((com.companyname.project.proto.Metadata.KeyValueProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.companyname.project.proto.Metadata.KeyValueProto other) {
        if (other == com.companyname.project.proto.Metadata.KeyValueProto.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.companyname.project.proto.Metadata.KeyValueProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.companyname.project.proto.Metadata.KeyValueProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:KeyValueProto)
    }

    static {
      defaultInstance = new KeyValueProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:KeyValueProto)
  }

  public interface KeyValueListProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:KeyValueListProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .KeyValueProto keyvalue = 1;</code>
     */
    java.util.List<com.companyname.project.proto.Metadata.KeyValueProto> 
        getKeyvalueList();
    /**
     * <code>repeated .KeyValueProto keyvalue = 1;</code>
     */
    com.companyname.project.proto.Metadata.KeyValueProto getKeyvalue(int index);
    /**
     * <code>repeated .KeyValueProto keyvalue = 1;</code>
     */
    int getKeyvalueCount();
    /**
     * <code>repeated .KeyValueProto keyvalue = 1;</code>
     */
    java.util.List<? extends com.companyname.project.proto.Metadata.KeyValueProtoOrBuilder> 
        getKeyvalueOrBuilderList();
    /**
     * <code>repeated .KeyValueProto keyvalue = 1;</code>
     */
    com.companyname.project.proto.Metadata.KeyValueProtoOrBuilder getKeyvalueOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code KeyValueListProto}
   */
  public static final class KeyValueListProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:KeyValueListProto)
      KeyValueListProtoOrBuilder {
    // Use KeyValueListProto.newBuilder() to construct.
    private KeyValueListProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeyValueListProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeyValueListProto defaultInstance;
    public static KeyValueListProto getDefaultInstance() {
      return defaultInstance;
    }

    public KeyValueListProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeyValueListProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                keyvalue_ = new java.util.ArrayList<com.companyname.project.proto.Metadata.KeyValueProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              keyvalue_.add(input.readMessage(com.companyname.project.proto.Metadata.KeyValueProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          keyvalue_ = java.util.Collections.unmodifiableList(keyvalue_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.companyname.project.proto.Metadata.internal_static_KeyValueListProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.companyname.project.proto.Metadata.internal_static_KeyValueListProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.companyname.project.proto.Metadata.KeyValueListProto.class, com.companyname.project.proto.Metadata.KeyValueListProto.Builder.class);
    }

    public static com.google.protobuf.Parser<KeyValueListProto> PARSER =
        new com.google.protobuf.AbstractParser<KeyValueListProto>() {
      public KeyValueListProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeyValueListProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeyValueListProto> getParserForType() {
      return PARSER;
    }

    public static final int KEYVALUE_FIELD_NUMBER = 1;
    private java.util.List<com.companyname.project.proto.Metadata.KeyValueProto> keyvalue_;
    /**
     * <code>repeated .KeyValueProto keyvalue = 1;</code>
     */
    public java.util.List<com.companyname.project.proto.Metadata.KeyValueProto> getKeyvalueList() {
      return keyvalue_;
    }
    /**
     * <code>repeated .KeyValueProto keyvalue = 1;</code>
     */
    public java.util.List<? extends com.companyname.project.proto.Metadata.KeyValueProtoOrBuilder> 
        getKeyvalueOrBuilderList() {
      return keyvalue_;
    }
    /**
     * <code>repeated .KeyValueProto keyvalue = 1;</code>
     */
    public int getKeyvalueCount() {
      return keyvalue_.size();
    }
    /**
     * <code>repeated .KeyValueProto keyvalue = 1;</code>
     */
    public com.companyname.project.proto.Metadata.KeyValueProto getKeyvalue(int index) {
      return keyvalue_.get(index);
    }
    /**
     * <code>repeated .KeyValueProto keyvalue = 1;</code>
     */
    public com.companyname.project.proto.Metadata.KeyValueProtoOrBuilder getKeyvalueOrBuilder(
        int index) {
      return keyvalue_.get(index);
    }

    private void initFields() {
      keyvalue_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getKeyvalueCount(); i++) {
        if (!getKeyvalue(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < keyvalue_.size(); i++) {
        output.writeMessage(1, keyvalue_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < keyvalue_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, keyvalue_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.companyname.project.proto.Metadata.KeyValueListProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.companyname.project.proto.Metadata.KeyValueListProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.companyname.project.proto.Metadata.KeyValueListProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.companyname.project.proto.Metadata.KeyValueListProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.companyname.project.proto.Metadata.KeyValueListProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.companyname.project.proto.Metadata.KeyValueListProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.companyname.project.proto.Metadata.KeyValueListProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.companyname.project.proto.Metadata.KeyValueListProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.companyname.project.proto.Metadata.KeyValueListProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.companyname.project.proto.Metadata.KeyValueListProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.companyname.project.proto.Metadata.KeyValueListProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KeyValueListProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:KeyValueListProto)
        com.companyname.project.proto.Metadata.KeyValueListProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.companyname.project.proto.Metadata.internal_static_KeyValueListProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.companyname.project.proto.Metadata.internal_static_KeyValueListProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.companyname.project.proto.Metadata.KeyValueListProto.class, com.companyname.project.proto.Metadata.KeyValueListProto.Builder.class);
      }

      // Construct using com.companyname.project.proto.Metadata.KeyValueListProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getKeyvalueFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (keyvalueBuilder_ == null) {
          keyvalue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          keyvalueBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.companyname.project.proto.Metadata.internal_static_KeyValueListProto_descriptor;
      }

      public com.companyname.project.proto.Metadata.KeyValueListProto getDefaultInstanceForType() {
        return com.companyname.project.proto.Metadata.KeyValueListProto.getDefaultInstance();
      }

      public com.companyname.project.proto.Metadata.KeyValueListProto build() {
        com.companyname.project.proto.Metadata.KeyValueListProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.companyname.project.proto.Metadata.KeyValueListProto buildPartial() {
        com.companyname.project.proto.Metadata.KeyValueListProto result = new com.companyname.project.proto.Metadata.KeyValueListProto(this);
        int from_bitField0_ = bitField0_;
        if (keyvalueBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            keyvalue_ = java.util.Collections.unmodifiableList(keyvalue_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.keyvalue_ = keyvalue_;
        } else {
          result.keyvalue_ = keyvalueBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.companyname.project.proto.Metadata.KeyValueListProto) {
          return mergeFrom((com.companyname.project.proto.Metadata.KeyValueListProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.companyname.project.proto.Metadata.KeyValueListProto other) {
        if (other == com.companyname.project.proto.Metadata.KeyValueListProto.getDefaultInstance()) return this;
        if (keyvalueBuilder_ == null) {
          if (!other.keyvalue_.isEmpty()) {
            if (keyvalue_.isEmpty()) {
              keyvalue_ = other.keyvalue_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureKeyvalueIsMutable();
              keyvalue_.addAll(other.keyvalue_);
            }
            onChanged();
          }
        } else {
          if (!other.keyvalue_.isEmpty()) {
            if (keyvalueBuilder_.isEmpty()) {
              keyvalueBuilder_.dispose();
              keyvalueBuilder_ = null;
              keyvalue_ = other.keyvalue_;
              bitField0_ = (bitField0_ & ~0x00000001);
              keyvalueBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getKeyvalueFieldBuilder() : null;
            } else {
              keyvalueBuilder_.addAllMessages(other.keyvalue_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getKeyvalueCount(); i++) {
          if (!getKeyvalue(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.companyname.project.proto.Metadata.KeyValueListProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.companyname.project.proto.Metadata.KeyValueListProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.companyname.project.proto.Metadata.KeyValueProto> keyvalue_ =
        java.util.Collections.emptyList();
      private void ensureKeyvalueIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          keyvalue_ = new java.util.ArrayList<com.companyname.project.proto.Metadata.KeyValueProto>(keyvalue_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.companyname.project.proto.Metadata.KeyValueProto, com.companyname.project.proto.Metadata.KeyValueProto.Builder, com.companyname.project.proto.Metadata.KeyValueProtoOrBuilder> keyvalueBuilder_;

      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public java.util.List<com.companyname.project.proto.Metadata.KeyValueProto> getKeyvalueList() {
        if (keyvalueBuilder_ == null) {
          return java.util.Collections.unmodifiableList(keyvalue_);
        } else {
          return keyvalueBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public int getKeyvalueCount() {
        if (keyvalueBuilder_ == null) {
          return keyvalue_.size();
        } else {
          return keyvalueBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public com.companyname.project.proto.Metadata.KeyValueProto getKeyvalue(int index) {
        if (keyvalueBuilder_ == null) {
          return keyvalue_.get(index);
        } else {
          return keyvalueBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public Builder setKeyvalue(
          int index, com.companyname.project.proto.Metadata.KeyValueProto value) {
        if (keyvalueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyvalueIsMutable();
          keyvalue_.set(index, value);
          onChanged();
        } else {
          keyvalueBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public Builder setKeyvalue(
          int index, com.companyname.project.proto.Metadata.KeyValueProto.Builder builderForValue) {
        if (keyvalueBuilder_ == null) {
          ensureKeyvalueIsMutable();
          keyvalue_.set(index, builderForValue.build());
          onChanged();
        } else {
          keyvalueBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public Builder addKeyvalue(com.companyname.project.proto.Metadata.KeyValueProto value) {
        if (keyvalueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyvalueIsMutable();
          keyvalue_.add(value);
          onChanged();
        } else {
          keyvalueBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public Builder addKeyvalue(
          int index, com.companyname.project.proto.Metadata.KeyValueProto value) {
        if (keyvalueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyvalueIsMutable();
          keyvalue_.add(index, value);
          onChanged();
        } else {
          keyvalueBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public Builder addKeyvalue(
          com.companyname.project.proto.Metadata.KeyValueProto.Builder builderForValue) {
        if (keyvalueBuilder_ == null) {
          ensureKeyvalueIsMutable();
          keyvalue_.add(builderForValue.build());
          onChanged();
        } else {
          keyvalueBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public Builder addKeyvalue(
          int index, com.companyname.project.proto.Metadata.KeyValueProto.Builder builderForValue) {
        if (keyvalueBuilder_ == null) {
          ensureKeyvalueIsMutable();
          keyvalue_.add(index, builderForValue.build());
          onChanged();
        } else {
          keyvalueBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public Builder addAllKeyvalue(
          java.lang.Iterable<? extends com.companyname.project.proto.Metadata.KeyValueProto> values) {
        if (keyvalueBuilder_ == null) {
          ensureKeyvalueIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, keyvalue_);
          onChanged();
        } else {
          keyvalueBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public Builder clearKeyvalue() {
        if (keyvalueBuilder_ == null) {
          keyvalue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          keyvalueBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public Builder removeKeyvalue(int index) {
        if (keyvalueBuilder_ == null) {
          ensureKeyvalueIsMutable();
          keyvalue_.remove(index);
          onChanged();
        } else {
          keyvalueBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public com.companyname.project.proto.Metadata.KeyValueProto.Builder getKeyvalueBuilder(
          int index) {
        return getKeyvalueFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public com.companyname.project.proto.Metadata.KeyValueProtoOrBuilder getKeyvalueOrBuilder(
          int index) {
        if (keyvalueBuilder_ == null) {
          return keyvalue_.get(index);  } else {
          return keyvalueBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public java.util.List<? extends com.companyname.project.proto.Metadata.KeyValueProtoOrBuilder> 
           getKeyvalueOrBuilderList() {
        if (keyvalueBuilder_ != null) {
          return keyvalueBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(keyvalue_);
        }
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public com.companyname.project.proto.Metadata.KeyValueProto.Builder addKeyvalueBuilder() {
        return getKeyvalueFieldBuilder().addBuilder(
            com.companyname.project.proto.Metadata.KeyValueProto.getDefaultInstance());
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public com.companyname.project.proto.Metadata.KeyValueProto.Builder addKeyvalueBuilder(
          int index) {
        return getKeyvalueFieldBuilder().addBuilder(
            index, com.companyname.project.proto.Metadata.KeyValueProto.getDefaultInstance());
      }
      /**
       * <code>repeated .KeyValueProto keyvalue = 1;</code>
       */
      public java.util.List<com.companyname.project.proto.Metadata.KeyValueProto.Builder> 
           getKeyvalueBuilderList() {
        return getKeyvalueFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.companyname.project.proto.Metadata.KeyValueProto, com.companyname.project.proto.Metadata.KeyValueProto.Builder, com.companyname.project.proto.Metadata.KeyValueProtoOrBuilder> 
          getKeyvalueFieldBuilder() {
        if (keyvalueBuilder_ == null) {
          keyvalueBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.companyname.project.proto.Metadata.KeyValueProto, com.companyname.project.proto.Metadata.KeyValueProto.Builder, com.companyname.project.proto.Metadata.KeyValueProtoOrBuilder>(
                  keyvalue_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          keyvalue_ = null;
        }
        return keyvalueBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:KeyValueListProto)
    }

    static {
      defaultInstance = new KeyValueListProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:KeyValueListProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KeyValueProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_KeyValueProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KeyValueListProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_KeyValueListProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016metadata.proto\"+\n\rKeyValueProto\022\013\n\003key" +
      "\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\"5\n\021KeyValueListPro" +
      "to\022 \n\010keyvalue\030\001 \003(\0132\016.KeyValueProtoB\037\n\035" +
      "com.companyname.project.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_KeyValueProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_KeyValueProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_KeyValueProto_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_KeyValueListProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_KeyValueListProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_KeyValueListProto_descriptor,
        new java.lang.String[] { "Keyvalue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
